title: brrr.wtf
logo: /assets/img/logo.png
description_strike: don't
description: panic.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
jekyll_compose:
  default_front_matter:
    posts:
      title:
      description:
      author: chase
      categories:
    drafts:
      title:
      description:
      author: chase
      categories:
plugins:
  - jekyll-paginate
  - jekyll-category-pages
paginate: 10
paginate_path: "blog/page:num"
permalink: /:year/:month/:day/:title:output_ext
