title: brrr.wtf
logo: /assets/img/logo.png
description_strike: don't
description: panic.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
jekyll_compose:
  default_front_matter:
    posts:
      title:
      description:
      author: chase
      tags:
    drafts:
      title:
      description:
      author: chase
      tags:        
